---
# handlers file for virtuoso

- name: clean source files
  file: 
    path: /var/tmp/virtuoso
    state: absent

- name: stop virtuoso
  systemd:
    name: virtuoso
    state: stopped

- name: reload systemctl
  command: systemctl daemon-reload

- name: remove build libs
  apt:
    state: absent
    pkg:
    - autoconf
    - automake
    - libtool
    - flex
    - bison
    - gperf
    - gawk
    - m4
    - make
    - openssl
    - libssl-dev