---
- name: Create list of repos to checkout
  set_fact: repos="{{ repositories.split(';') }}"

- name: Clone each repo from list in its individual folder
  git:
    repo: '{{ item }}'
    dest: /var/git/{{ item | basename }}  # Basename gathers the name of the repository from the URL.
  with_items:
  -  "{{ repos }}"
...
