---
- name: Update aptitude cache and install dependencies.
  apt:
    pkg={{ item }}
    state=present 
    update_cache=yes 
    cache_valid_time=3600
  with_items:
    - autoconf
    - automake
    - bison
    - flex
    - gawk
    - git
    - gperf
    - libtool
    - libssl-dev
    - m4
    - make
    - openssl

- name: Clone stable/7 branch of Virtuoso Github repo.
  git: 
    repo=https://github.com/openlink/virtuoso-opensource
    dest=/var/tmp/virtuoso
    version=stable/7

- name: Autogen the Virtuoso build configuration
  shell: /var/tmp/virtuoso/autogen.sh 
    chdir=/var/tmp/virtuoso 
    creates=/var/tmp/virtuoso/autogen.log
    executable=/bin/bash

- name: Configure Makefile.
  command: /var/tmp/virtuoso/configure --prefix={{ virtuoso_install_dir }}
    chdir=/var/tmp/virtuoso
    creates=/var/tmp/virtuoso/Makefile
  environment:
    cflags: "-O2 -m64"

- name: Build Virtuoso from source.
  command: make install
    chdir=/var/tmp/virtuoso
    creates="{{ virtuoso_install_dir }}/bin/virtuoso-t"

- name: Copy isql file to enable sparql
  copy: src=virtuoso.isql dest=/var/tmp/virtuoso.isql

- name: Create Virtuoso service unit file
  template:
    src: virtuoso.service.j2
    dest: /lib/systemd/system/teamcity.service
    mode: 644
    notify:
      - reload systemctl

- name: Start virtuoso 
  systemd:
    state: started

- name: Wait for virtuoso port to be open
  wait_for: port=1111 delay=10

- name: Run isql script to enable sparql permissions.
  command: "{{ virtuoso_install_dir }}/bin/isql 1111 dba dba VERBOSE=OFF BANNER=OFF PROMPT=OFF ECHO=OFF BLOBS=ON ERRORS=stdout /var/tmp/virtuoso.isql"
  notify:
    - stop virtuoso
    - clean source files
    - remove build libs
...